### ISSUE TITLE
Window#move does not change the window's position and returns -1

### ISSUE THREAD

**Issue by snacks02** [maiha/crt.cr#17]
I'm trying to draw a window above another window, but it remains at the starting position

Code:
```crystal
win = Crt::Window.new(8, 16)
win.move(30, 30)
win.border
win.refresh
```
Result
![image](https://user-images.githubusercontent.com/41530422/76733636-67559b00-678b-11ea-9c80-88b63acdcfad.png)

**Comment by maiha** [comment]
I'm not well familiar with **curses** , but I think `move` is an operation about text.
Could you try x, y on `Window` ?

```crystal
module Crt
  class Window
     def initialize(@row = -1, @col = -1, y = 0, x = 0)
```

**Comment by snacks02** [comment]
Yup. If I'm changing `x` and `y` then it works nice.
The solution is inheritance then I guess? Something like this:
```crystal
class SecondWindow < Crt::Window
  def initialize(@row = -1, @col = -1, y = 3, x = 3)
    Crt.init
    @row = Crt.y if @row < 0
    @col = Crt.x if @col < 0
    @winp = LibNcursesw.newwin(@row, @col, y, x)
  end
end
```
![image](https://user-images.githubusercontent.com/41530422/76745434-0dab9b80-67a0-11ea-81fb-d1e2e64454f7.png)

**Comment by sanks-ty** [comment]
Could as well replace `x`, `y` with instance variables `@x`, `@y`

**Comment by maiha** [comment]
Running the crystal and c libraries works much the same. So it would be nice to find a sample of c that works for ncurses multiple windows first.

Then, I can help you with how to translate the c sample to the crystal, or how to write it in crt.cr.

**Comment by snacks02** [comment]
Added the desired function. See #18
